// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0oB4Hzdt1HMOuwr6yt_-lj-4RBob4LgY',
    appId: '1:61937012603:web:bfde251f355817d07f77de',
    messagingSenderId: '61937012603',
    projectId: 'tasklistapp-4a364',
    authDomain: 'tasklistapp-4a364.firebaseapp.com',
    storageBucket: 'tasklistapp-4a364.firebasestorage.app',
    measurementId: 'G-N5F05617CE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfc-jv7VpR-7Drhixp89h_4Zg3ZKxOLV8',
    appId: '1:61937012603:android:f0fe11a412d94a037f77de',
    messagingSenderId: '61937012603',
    projectId: 'tasklistapp-4a364',
    storageBucket: 'tasklistapp-4a364.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvMvp6DdN7T2IJcZ3f-t3Pdjt2lCf15vk',
    appId: '1:61937012603:ios:02ecf0caf2e1756d7f77de',
    messagingSenderId: '61937012603',
    projectId: 'tasklistapp-4a364',
    storageBucket: 'tasklistapp-4a364.firebasestorage.app',
    iosBundleId: 'com.example.tasklist',
  );
}
